include:
  - project: $_GITLAB_TEMPLATES_REPO
    ref: $_GITLAB_TEMPLATES_REF
    file:
      - '/includes/include.drupalci.main.yml'
      - '/includes/include.drupalci.variables.yml'
      - '/includes/include.drupalci.workflows.yml'

variables:
  OPT_IN_TEST_NEXT_MINOR: 1
  OPT_IN_TEST_NEXT_MAJOR: 1
  OPT_IN_TEST_MAX_PHP: 1
  OPT_IN_TEST_PREVIOUS_MAJOR: 1
  OPT_IN_TEST_PREVIOUS_MINOR: 1
  _CSPELL_IGNORE_PATHS: 'tests/fixtures'
  _CSPELL_WORDS: varchar

composer (previous major):
  after_script:
    - composer remove drupal/history
  variables:
    _LENIENT_ALLOW_LIST: "history"
composer (previous minor):
  after_script:
    - composer remove drupal/history
  variables:
    _LENIENT_ALLOW_LIST: "history"
composer (next major):
  variables:
    _LENIENT_ALLOW_LIST: "history"
